### ISSUE TITLE
Module works but randomnly stops after a few hours

### ISSUE THREAD

**Issue by web-orbit12** [HuskyDG/MagiskHide#11]
As the title says, the module seems to be working and effectively hides root. Banking apps work perfectly, however after a few hours it stops working. After rebooting it will work again but then the same issue occurs again. 

I'm using Samsung s21+

Not sure if i can provide a log that will capture this issue since it happens randomnly. Let me know how i can provide more useful info about this if needed. 

Edit: I tried to time it. The issue happened after 5 hours, really weird. Only way to get the module working again is by restarting the phone.

**Comment by sas46** [comment]
> As the title says, the module seems to be working and effectively hides root. Banking apps work perfectly, however after a few hours it stops working. After rebooting it will work again but then the same issue occurs again.
> 
> I'm using Samsung s21+
> 
> Not sure if i can provide a log that will capture this issue since it happens randomnly. Let me know how i can provide more useful info about this if needed.
> 
> Edit: I tried to time it. The issue happened after 5 hours, really weird. Only way to get the module working again is by restarting the phone.


Same happens with me but occurs after a few days, not hours
Restarting fixes it

**Comment by web-orbit12** [comment]
> Same happens with me but occurs after a few days, not hours Restarting fixes it

Would you mind giving some info on what type of configuration you're using and what modules?

**Comment by sas46** [comment]
> > Same happens with me but occurs after a few days, not hours Restarting fixes it
> 
> Would you mind giving some info on what type of configuration you're using and what modules?

Of course
Pixel 6 Pro, Android 13 build TQ3A.230705.001
Magisk  26.1 (26100), App 26.1 (26100)
Modules: Busybox for Android NDK 1.34.1 by osm0sis
MagiskHide 1.10.3 by HuskyDG @MagiskDelta
SQLite3 Universal Binaries v1.4 by 73sydney
Systemless Hosts 1.0
Universal SafetyNet Fix v2.4.0-MOD_1.2 by kdrag0n, modded by Displax

**Comment by web-orbit12** [comment]
> Of course Pixel 6 Pro, Android 13 build TQ3A.230705.001 Magisk 26.1 (26100), App 26.1 (26100) Modules: Busybox for Android NDK 1.34.1 by osm0sis MagiskHide 1.10.3 by HuskyDG @MagiskDelta SQLite3 Universal Binaries v1.4 by 73sydney Systemless Hosts 1.0 Universal SafetyNet Fix v2.4.0-MOD_1.2 by kdrag0n, modded by Displax

Seems we have the same config. Except i dont have busybox and sqlite3. Zygisk is turnt off also.

**Comment by web-orbit12** [comment]
@sas46 hi mate i installed magisk delta and it seems to fix the issue. Used magiskhide and enforced sulist. I can even use zygisk without it being detected.
